// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/company_profile.grpc.proto

package com.wanpng.employers-users.grpc.domain;

public interface CompanyProfileGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.CompanyProfileGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string company_name = 2;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 2;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();
}
