// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/job_posting_service.grpc.proto

package com.wanpng.employers-users.grpc.service;

public final class EmployersUsersServiceProtos {
  private EmployersUsersServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_UpdateCompanyProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_UpdateCompanyProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_UpdateCompanyProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_UpdateCompanyProfileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-protos/service/job_posting_service.grp" +
      "c.proto\022\016protos.service\032\'protos/domain/c" +
      "ompanyprofile.grpc.proto\"Z\n\033UpdateCompan" +
      "yProfileRequest\022;\n\020employer_profile\030\001 \001(" +
      "\0132!.protos.domain.CompanyProfileGrpc\"3\n\034" +
      "UpdateCompanyProfileResponse\022\023\n\013employer" +
      "_id\030\001 \001(\t2\212\001\n\025EmployersUsersService\022q\n\024U" +
      "pdateCompanyProfile\022+.protos.service.Upd" +
      "ateCompanyProfileRequest\032,.protos.servic" +
      "e.UpdateCompanyProfileResponseB}\n\'com.wa" +
      "npng.employers-users.grpc.serviceB\033Emplo" +
      "yersUsersServiceProtosP\001Z3github.com/wan" +
      "png/employers-users-grpc/grpc/serviceb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.employers-users.grpc.domain.CompanyProfileGrpcProtos.getDescriptor(),
        });
    internal_static_protos_service_UpdateCompanyProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_UpdateCompanyProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_UpdateCompanyProfileRequest_descriptor,
        new java.lang.String[] { "EmployerProfile", });
    internal_static_protos_service_UpdateCompanyProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_UpdateCompanyProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_UpdateCompanyProfileResponse_descriptor,
        new java.lang.String[] { "EmployerId", });
    com.wanpng.employers-users.grpc.domain.CompanyProfileGrpcProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
