// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employers_users_service.grpc.proto

package com.wanpng.employers-users.grpc.service;

public interface UpdateCompanyProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.UpdateCompanyProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.CompanyProfileGrpc company_profile = 1;</code>
   * @return Whether the companyProfile field is set.
   */
  boolean hasCompanyProfile();
  /**
   * <code>.protos.domain.CompanyProfileGrpc company_profile = 1;</code>
   * @return The companyProfile.
   */
  com.wanpng.employers-users.grpc.domain.CompanyProfileGrpc getCompanyProfile();
  /**
   * <code>.protos.domain.CompanyProfileGrpc company_profile = 1;</code>
   */
  com.wanpng.employers-users.grpc.domain.CompanyProfileGrpcOrBuilder getCompanyProfileOrBuilder();
}
