// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/employer_service.grpc.proto

package com.wanpng.employers-users.grpc.service;

public interface UpdateCompanyProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.UpdateCompanyProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.CompanyProfileGrpc employer_profile = 1;</code>
   * @return Whether the employerProfile field is set.
   */
  boolean hasEmployerProfile();
  /**
   * <code>.protos.domain.CompanyProfileGrpc employer_profile = 1;</code>
   * @return The employerProfile.
   */
  com.wanpng.employers-users.grpc.service.CompanyProfileGrpc getEmployerProfile();
  /**
   * <code>.protos.domain.CompanyProfileGrpc employer_profile = 1;</code>
   */
  com.wanpng.employers-users.grpc.service.CompanyProfileGrpcOrBuilder getEmployerProfileOrBuilder();
}
